### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by L-Gaudet** [eshayamani/ScratchQL#1]
Some things that can be tweaked:
* The `design-blocks` folder seems to be redundant as it contains everything within `src/`, including the index and style files. 
* Adding some documentation on how to run/install the program in the main `README.md` file. This is pretty standard across open source projects, having setup documentation in the main readme, and then more in-depth documentation elsewhere. 
* It might be a good idea to have a cloud hosted database, since having a user install and setup mySQL and additionally download and setup a database file is quite a bit of work and can be confusing for people who haven't done something like that before. And those type of people are a big part of the target market for this project I believe.

**Comment by eshayamani** [comment]
Thanks for pointing out the design blocks folder. I don't think we realized it was formatted that way.
We are currently looking into a cloud-hosted database and have been working on how to integrate that into our project.
